### PR TITLE
Docs: add tests requirements to README.md

### PR DESCRIPTION
**Pull request by gustavokrieger**

### CODE REVIEW

**Comment by benmezger** [comment]
Awesome!

**Review by benmezger — APPROVED** [review]

**Comment by benmezger** [comment]
you can update your branch with master (not required), as it seems you still have the old branch (with the circleci configuration)

In this branch: 

```
git fetch --all
git rebase origin/master
```

**Comment by gustavokrieger** [comment]
Wait, I'm pretty sure I did it before committing. I rebased it now and nothing changed...
What makes you say that I may have the old branch?

**Comment by benmezger** [comment]
> Wait, I'm pretty sure I did it before committing. I rebased it now and nothing changed...

Hmm, you are right, seems that there is no `circleci` file in your branch: https://github.com/CheesecakeLabs/gjira/tree/add-tests-requirements-to-readme

> What makes you say that I may have the old branch?

Because it seems that circle CI is waiting for a status to be reported even though we removed circle ci. Might be a link integration through circleci to this repo. I will have to look into this. But as of now, everything is cool, we can ignore it.

**Review by gustavuka — APPROVED** [review]

**Review by matpfernandes — APPROVED** [review]

**Pull request merged**
